# Generated by Django 4.2.3 on 2023-09-24 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DAInquiry',
            new_name='Inquiry',
        ),
    ]
