# Generated by Django 4.2.3 on 2023-09-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_rename_dainquiry_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='title',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='subject',
            field=models.CharField(default='', max_length=100, verbose_name='件名'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='name',
            field=models.CharField(max_length=100, verbose_name='お名前'),
        ),
    ]
