# Generated by Django 4.2.3 on 2023-09-28 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='当社番号')),
                ('type', models.CharField(blank=True, max_length=10, null=True, verbose_name='ボディ・レンズ・他')),
                ('featured', models.BooleanField(blank=True, null=True, verbose_name='お勧め')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='品名')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='製造番号')),
                ('estimate', models.CharField(blank=True, max_length=10, null=True, verbose_name='評価')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='並び')),
                ('close', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('custom_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
