# Generated by Django 4.2.3 on 2023-09-28 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '出品品目', 'verbose_name_plural': '出品品目'},
        ),
        migrations.AlterModelTable(
            name='item',
            table='da_item',
        ),
    ]
