# Generated by Django 4.2.3 on 2023-09-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_stat_bidhistory_bid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='stat',
            table='da_stat',
        ),
    ]
