# Generated by Django 4.2.3 on 2023-09-28 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_stat_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='access_cnt',
            new_name='access_count',
        ),
    ]
