# Generated by Django 4.2.3 on 2023-09-28 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_rename_access_cnt_stat_access_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stat',
            old_name='strat_price',
            new_name='start_price',
        ),
    ]
