# Generated by Django 4.2.3 on 2023-09-29 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0007_rename_strat_price_stat_start_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='custom_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
