# Generated by Django 4.2.3 on 2023-09-29 01:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('item', '0010_alter_bid_custom_user_alter_bidhistory_custom_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='custom_user',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='winner_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
