# Generated by Django 4.2.3 on 2023-10-07 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_watch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='メーカーID')),
                ('maker_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='メーカー名')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='並び')),
            ],
            options={
                'verbose_name': 'メーカー',
                'verbose_name_plural': 'メーカー',
                'db_table': 'da_maker',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='maker',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='item_maker', to='item.maker'),
        ),
    ]
