# Generated by Django 4.2.3 on 2023-10-07 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_maker_item_maker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='maker',
        ),
        migrations.DeleteModel(
            name='Maker',
        ),
    ]
