# Generated by Django 4.2.3 on 2023-10-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_remove_item_maker_delete_maker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='メーカーID')),
                ('maker_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='メーカー名')),
                ('sort', models.IntegerField(blank=True, null=True, verbose_name='並び')),
            ],
            options={
                'verbose_name': 'メーカー',
                'verbose_name_plural': 'メーカー',
                'db_table': 'da_maker',
            },
        ),
    ]
