# Generated by Django 4.2.3 on 2023-10-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_item_maker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='start_price',
        ),
        migrations.AddField(
            model_name='item',
            name='start_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='スタート金額'),
        ),
    ]
