# Generated by Django 4.2.3 on 2023-10-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_remove_stat_start_price_item_start_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='評価ID')),
                ('estimate_display', models.CharField(blank=True, max_length=200, null=True, verbose_name='評価')),
            ],
            options={
                'verbose_name': '評価',
                'verbose_name_plural': '評価',
                'db_table': 'da_estimate',
            },
        ),
    ]
