# Generated by Django 4.2.3 on 2023-10-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_estimate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('chapter', models.CharField(blank=True, max_length=20, null=True, verbose_name='章')),
                ('article', models.CharField(blank=True, max_length=50, null=True, verbose_name='条')),
                ('body', models.CharField(blank=True, max_length=500, null=True, verbose_name='本文')),
            ],
            options={
                'verbose_name': '規約',
                'verbose_name_plural': '規約',
                'db_table': 'da_rule',
            },
        ),
    ]
