# Generated by Django 4.2.3 on 2023-10-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='option',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='附則'),
        ),
    ]
