# Generated by Django 4.2.3 on 2023-10-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_rule_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='featured',
            field=models.IntegerField(blank=True, null=True, verbose_name='お勧め'),
        ),
    ]
