# Generated by Django 4.2.3 on 2023-10-22 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_alter_item_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='maker',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='item_maker', to='item.maker', verbose_name='メーカー'),
        ),
    ]
