# Generated by Django 4.2.3 on 2023-10-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_alter_item_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='body',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='本文'),
        ),
    ]
