# Generated by Django 4.2.3 on 2023-10-25 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_alter_stat_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='item',
            field=models.ForeignKey(blank=True, default='1', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='winner_item', to='item.item'),
        ),
    ]
