# Generated by Django 4.2.3 on 2023-10-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0030_alter_stat_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='access_count',
            field=models.IntegerField(default='0', verbose_name='アクセス数'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='bid_count',
            field=models.IntegerField(default='0', verbose_name='入札回数'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='win_price',
            field=models.IntegerField(default='0', verbose_name='落札金額'),
        ),
    ]
