# Generated by Django 4.2.3 on 2023-11-02 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0031_alter_stat_access_count_alter_stat_bid_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'アイテム', 'verbose_name_plural': 'アイテム'},
        ),
    ]
