# Generated by Django 4.2.3 on 2023-09-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='avater',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='company',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='position',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='市区町村'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='block',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='番地'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='建物等'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='会社名または屋号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='古物許可証番号'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='モバイル'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='連絡先'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prefecture',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='都道府県'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='representative_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='代表者'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='zip',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=200, unique=True, verbose_name='メール'),
        ),
        migrations.DeleteModel(
            name='HistoricalCustomUser',
        ),
    ]
