# Generated by Django 4.2.3 on 2023-10-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': '会員', 'verbose_name_plural': '会員'},
        ),
    ]
