# Generated by Django 4.2.3 on 2023-10-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='fee',
        ),
    ]
