# Generated by Django 4.2.3 on 2023-09-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('setion', models.CharField(max_length=100, verbose_name='名称')),
                ('subscriptionByYear', models.IntegerField(verbose_name='年会費')),
                ('display', models.IntegerField(verbose_name='出品手数料')),
                ('commission', models.IntegerField(verbose_name='成約手数料')),
                ('bidding', models.IntegerField(verbose_name='落札手数料')),
                ('set_display', models.IntegerField(verbose_name='出品手数料（セット品）')),
                ('set_commission', models.IntegerField(verbose_name='成約手数料（セット品）')),
                ('started', models.DateTimeField(verbose_name='適用日開始')),
                ('ended', models.DateTimeField(verbose_name='適用日終了')),
            ],
            options={
                'verbose_name': '年会費及び手数料',
                'verbose_name_plural': '年会費及び手数料',
                'db_table': 'da_fee',
            },
        ),
    ]
