# Generated by Django 4.2.3 on 2023-09-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='bidding',
            field=models.IntegerField(blank=True, null=True, verbose_name='落札手数料'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='commission',
            field=models.IntegerField(blank=True, null=True, verbose_name='成約手数料'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='display',
            field=models.IntegerField(blank=True, null=True, verbose_name='出品手数料'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='ended',
            field=models.DateTimeField(blank=True, null=True, verbose_name='適用日終了'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='set_commission',
            field=models.IntegerField(blank=True, null=True, verbose_name='成約手数料（セット品）'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='set_display',
            field=models.IntegerField(blank=True, null=True, verbose_name='出品手数料（セット品）'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='setion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='started',
            field=models.DateTimeField(blank=True, null=True, verbose_name='適用日開始'),
        ),
        migrations.AlterField(
            model_name='fee',
            name='subscriptionByYear',
            field=models.IntegerField(blank=True, null=True, verbose_name='年会費'),
        ),
    ]
