# Generated by Django 4.2.3 on 2023-09-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0004_fee_top_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='featured',
            field=models.CharField(blank=True, default='on', max_length=20, null=True, verbose_name='お勧めプラン'),
        ),
    ]
