# Generated by Django 4.2.3 on 2023-09-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0007_alter_apply_license_number_alter_apply_mobile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
