# Generated by Django 4.2.3 on 2023-10-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0009_userfee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFee',
        ),
    ]
