# Generated by Django 4.2.3 on 2023-11-02 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fee', '0012_fee_bidding_margin_fee_commission_margin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfee',
            options={'verbose_name': '会員年会費・手数料', 'verbose_name_plural': '会員年会費・手数料'},
        ),
        migrations.RemoveField(
            model_name='fee',
            name='set_commission',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='set_display',
        ),
        migrations.AlterField(
            model_name='userfee',
            name='custom_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_fee_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Offset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('display_count', models.IntegerField(blank=True, null=True, verbose_name='出品点数')),
                ('display_sum', models.IntegerField(blank=True, null=True, verbose_name='出品料')),
                ('commission_count', models.IntegerField(blank=True, null=True, verbose_name='成約点数')),
                ('commission_sum', models.IntegerField(blank=True, null=True, verbose_name='成約料')),
                ('bidding_count', models.IntegerField(blank=True, null=True, verbose_name='落札点数')),
                ('bidding_sum', models.IntegerField(blank=True, null=True, verbose_name='落札料')),
                ('close', models.DateTimeField(blank=True, null=True, verbose_name='終了日時')),
                ('custom_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offset_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'オークション相殺表',
                'verbose_name_plural': 'オークション相殺表',
                'db_table': 'da_offset',
            },
        ),
    ]
