# Generated by Django 4.2.3 on 2023-11-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0013_alter_userfee_options_remove_fee_set_commission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offset',
            name='counterbalance',
            field=models.IntegerField(blank=True, null=True, verbose_name='相殺金額'),
        ),
    ]
