# Generated by Django 4.2.3 on 2023-11-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0015_rename_bidding_sum_offset_bidding_fee_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='systemUsageByYear',
            field=models.IntegerField(blank=True, null=True, verbose_name='システム利用料/回'),
        ),
    ]
