# Generated by Django 4.2.3 on 2023-11-02 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0016_alter_fee_systemusagebyyear'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='display',
        ),
        migrations.RemoveField(
            model_name='offset',
            name='display_count',
        ),
        migrations.RemoveField(
            model_name='offset',
            name='display_fee_sum',
        ),
    ]
