# Generated by Django 4.2.3 on 2023-11-03 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fee', '0017_remove_fee_display_remove_offset_display_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='custom_user',
            field=models.ManyToManyField(through='fee.UserFee', to=settings.AUTH_USER_MODEL),
        ),
    ]
