# Generated by Django 4.2.3 on 2023-11-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0018_fee_custom_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='消費税率')),
                ('started', models.DateTimeField(blank=True, null=True, verbose_name='適用日開始')),
                ('ended', models.DateTimeField(blank=True, null=True, verbose_name='適用日終了')),
            ],
            options={
                'verbose_name': '消費税率',
                'verbose_name_plural': '消費税率',
                'db_table': 'da_tax',
            },
        ),
    ]
