# Generated by Django 4.2.3 on 2023-10-06 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('path_id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.CharField(db_column='path', default='', max_length=255, null=True)),
            ],
            options={
                'db_table': 'da_path',
            },
        ),
        migrations.CreateModel(
            name='PathXGroup',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('path_x_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_id', models.ForeignKey(db_column='group_id', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('path_id', models.ForeignKey(db_column='path_id', default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='config.path')),
            ],
            options={
                'db_table': 'da_path_x_group',
            },
        ),
    ]
