"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from .base import *

SECRET_KEY = ''

ALLOWED_HOSTS = ['*']
INTERNAL_IPS = ['127.0.0.1']

MIDDLEWARE += [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

INSTALLED_APPS += [
    'debug_toolbar',
]

DATABASES = {
    'default': {
        'ENGINE'   : 'django.db.backends.mysql',
        'NAME'     : 'AuctionHub',
        'USER'     : '',
        'PASSWORD' : '',
        'HOST'     : 'localhost',
        'PORT'     : '3306',
        'ATOMIC_REQUESTS': True,
    }  
}

EMAIL_BACKEND = "anymail.backends.sendinblue.EmailBackend"
EMAIL_HOST = 'localhost'
EMAIL_HOST_USER = 'hitoshi1964@gmail.com'
EMAIL_HOST_PASSWORD = 'メールサーバーのパスワード'
EMAIL_USE_TLS = False
DEFAULT_FROM_EMAIL = 'sender@example.com'
ANYMAIL = {
    "SENDINBLUE_API_KEY": "",
}

LOGGING = {
#バージョンは 「1」 固定
'version': 1,
#既存のログ設定を無効化しない
    'disable_existing_loggers': False,
    #ログフォーマット
    'formatters': {
        #本番⽤
        'production': {
            'format': '%(asctime)s [%(levelname)s] %(process)d %(thread)d '
                      '%(pathname)s:%(lineno)d %(message)s'
            },
    },
    #ハンドラ
    'handlers': {
        #ファイル出⼒⽤ハンドラ
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': '/Volumes/sd/Sites/DjangoProject/assets/logs/app.log'.format(PROJECT_NAME),
            'formatter': 'production',
        },
    },
    #ロガー
    'loggers': {
        #⾃作アプリケーション全般のログを拾うロガー
        '': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        #Django本体が出すログ全般を拾うロガー
        'django': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        #発⾏される SQL⽂を出⼒するための設定  
        'django.db.backends': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
} 
 