# Generated by Django 4.2.3 on 2023-09-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('deleted', models.DateTimeField(blank=True, null=True, verbose_name='削除日時')),
                ('license_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='古物許可証番号')),
                ('representative_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='代表者')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='会社名または屋号')),
                ('zip', models.CharField(blank=True, max_length=10, null=True, verbose_name='郵便番号')),
                ('prefecture', models.CharField(blank=True, max_length=10, null=True, verbose_name='都道府県')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='市区町村')),
                ('block', models.CharField(blank=True, max_length=100, null=True, verbose_name='番地')),
                ('building', models.CharField(blank=True, max_length=100, null=True, verbose_name='建物等')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='連絡先')),
                ('mobile_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='モバイル')),
                ('mail', models.EmailField(blank=True, max_length=200, null=True, verbose_name='メール')),
            ],
            options={
                'verbose_name': '加入申し込み',
                'verbose_name_plural': '加入申し込み',
                'db_table': 'da_apply',
            },
        ),
    ]
