# Generated by Django 4.2.3 on 2023-09-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_apply_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apply',
            name='mail',
        ),
        migrations.AddField(
            model_name='apply',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='メール'),
        ),
    ]
