# Generated by Django 4.2.3 on 2023-10-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='メール本文'),
        ),
    ]
