# Generated by Django 4.2.3 on 2023-10-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_mail_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='body',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='メール本文'),
        ),
    ]
